// Package channeler is a cli generator to generate channeled version of a type.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/parser"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/mh-cbon/astutil"
)

var name = "channeler"
var version = "0.0.0"

func main() {

	var help bool
	var h bool
	var ver bool
	var v bool
	var outPkg string
	flag.BoolVar(&help, "help", false, "Show help.")
	flag.BoolVar(&h, "h", false, "Show help.")
	flag.BoolVar(&ver, "version", false, "Show version.")
	flag.BoolVar(&v, "v", false, "Show version.")
	flag.StringVar(&outPkg, "p", os.Getenv("GOPACKAGE"), "Package name of the new code.")

	flag.Parse()

	if ver || v {
		showVer()
		return
	}
	if help || h {
		showHelp()
		return
	}

	if flag.NArg() < 2 {
		panic("wrong usage")
	}
	args := flag.Args()

	gopath := filepath.Join(os.Getenv("GOPATH"), "src")
	pkgToLoad, err := os.Getwd()
	if err != nil {
		panic(err)
	}
	pkgToLoad = pkgToLoad[len(gopath)+1:]
	dest := os.Stdout

	o := args[0]
	restargs := args[1:]

	prog := astutil.GetProgram(pkgToLoad).Package(pkgToLoad)
	// astutil.PrintPkg(p)

	foundTypes := astutil.FindTypes(prog)
	foundMethods := astutil.FindMethods(prog)
	foundCtors := astutil.FindCtors(prog, foundTypes)

	if o != "-" {
		f, err := os.Create(o)
		if err != nil {
			panic(err)
		}
		dest = f
		defer func() {
			f.Close()
			exec.Command("go", "fmt", args[0]).Run()
		}()
	}

	fmt.Fprintf(dest, "package %v\n\n", outPkg)
	fmt.Fprintln(dest, `// file generated by`)
	fmt.Fprintf(dest, "// github.com.mh-cbon/%v\n", name)
	fmt.Fprintln(dest, `// do not edit`)
	fmt.Fprintln(dest, ``)

	for _, todo := range restargs {
		y := strings.Split(todo, ":")
		if len(y) != 2 {
			panic("wrong name " + todo)
		}
		srcName := y[0]
		destName := y[1]

		res := processType(destName, srcName, foundCtors, foundMethods)
		io.Copy(dest, &res)
	}
}

func showVer() {
	fmt.Printf("%v %v\n", name, version)
}

func showHelp() {
	showVer()
	fmt.Println()
	fmt.Println("Usage")
	fmt.Println()
	fmt.Printf("	%v [-p name] [out] [...types]\n\n", name)
	fmt.Printf("	out:   Output destination of the results, use '-' for stdout.\n")
	fmt.Printf("	types: A list of types such as src:dst.\n")
	fmt.Printf("	-p:    The name of the package output.\n")
	fmt.Println()
}

func processType(destName, srcName string, foundCtors map[string]*ast.FuncDecl, foundMethods map[string][]*ast.FuncDecl) bytes.Buffer {

	var b bytes.Buffer
	dest := &b

	fmt.Fprintf(dest, `
// %v is channeled.
type %v struct{
	embed %v
	ops chan func()
	stop chan bool
}
		`, destName, destName, srcName)

	ctorParams := ""
	ctorParamsInvokation := ""
	ctorName := ""
	ctorIsPointer := false
	srcConcrete := astutil.GetUnpointedType(srcName)
	if x, ok := foundCtors[srcConcrete]; ok {
		withEllipse := astutil.MethodHasEllipse(x)
		ctorParamsInvokation = astutil.MethodParamNamesInvokation(x, withEllipse)
		ctorParams = astutil.MethodParams(x)
		ctorIsPointer = astutil.MethodReturnPointer(x)
		ctorName = "New" + srcConcrete
	}

	if !(astutil.IsAPointedType(srcName) == ctorIsPointer) {
		ctorParams = ""
	}

	fmt.Fprintf(dest, `// New%v constructs a chenneled version of %v
func New%v(%v) *%v {
	ret := &%v{
		ops: make(chan func()),
		stop: make(chan bool),
	}
`,
		destName, srcName, destName, ctorParams, destName, destName)

	if ctorName != "" && astutil.IsAPointedType(srcName) == ctorIsPointer {
		fmt.Fprintf(dest, "	ret.embed = %v(%v)\n", ctorName, ctorParamsInvokation)
	}
	fmt.Fprintf(dest, "	go ret.Start()\n")
	fmt.Fprintf(dest, "	return ret\n")
	fmt.Fprintf(dest, "}\n")

	fmt.Fprintf(dest, `// Start the main loop
func (t *%v) Start(){
	for {
		select{
		case op:=<-t.ops:
			op()
		case <-t.stop:
			return
		}
	}
}`,
		destName)

	fmt.Fprintln(dest)
	fmt.Fprintf(dest, `// Stop the main loop
func (t *%v) Stop(){
	t.stop <- true
}`,
		destName)
	fmt.Fprintln(dest)

	for _, m := range foundMethods[srcConcrete] {
		paramNames := astutil.MethodParamNames(m)
		// receiverName := astutil.ReceiverName(m)
		methodName := astutil.MethodName(m)
		varExpr := ""
		assignExpr := ""
		callExpr := fmt.Sprintf("%v.embed.%v(%v)", "t", methodName, paramNames)
		returnExpr := ""
		methodReturnTypes := astutil.MethodReturnTypes(m)
		if len(methodReturnTypes) > 0 {
			retVars := astutil.MethodReturnVars(m)
			varExpr = fmt.Sprintf("var ")
			for i, r := range retVars {
				varExpr += r + " " + methodReturnTypes[i] + ", "
			}
			varExpr = varExpr[:len(varExpr)-2]
			assignExpr = fmt.Sprintf("%v = ", strings.Join(retVars, ", "))
			returnExpr = fmt.Sprintf("return %v", strings.Join(retVars, ", "))
		}
		sExpr := fmt.Sprintf(`
	%v
	t.ops<-func() {%v%v}
	%v
`, varExpr, assignExpr, callExpr, returnExpr)
		sExpr = fmt.Sprintf(`func(){%v}`, sExpr)
		expr, err := parser.ParseExpr(sExpr)
		if err != nil {
			panic(err)
		}
		astutil.SetReceiverName(m, "t")
		astutil.SetReceiverTypeName(m, destName)
		astutil.SetReceiverPointer(m, true)
		m.Body = expr.(*ast.FuncLit).Body
		fmt.Fprintf(dest, "// %v is channeled\n", methodName)
		fmt.Fprintf(dest, "%v\n", astutil.Print(m))
	}

	return b
}
