package main

// file generated by
// github.com/mh-cbon/channeler
// do not edit

// MyTomate is channeled.
type MyTomate struct {
	embed Tomate
	ops   chan func()
	stop  chan bool
	tick  chan bool
}

// NewMyTomate constructs a channeled version of Tomate
func NewMyTomate() *MyTomate {
	ret := &MyTomate{
		ops:  make(chan func()),
		tick: make(chan bool),
		stop: make(chan bool),
	}
	go ret.Start()
	return ret
}

// Start the main loop
func (t *MyTomate) Start() {
	for {
		select {
		case op := <-t.ops:
			op()
			t.tick <- true
		case <-t.stop:
			return
		}
	}
}

// Stop the main loop
func (t *MyTomate) Stop() {
	t.stop <- true
}

// Hello is channeled
func (t *MyTomate) Hello() {
	t.ops <- func() {
		t.embed.Hello()
	}
	<-t.tick
}

// Good is channeled
func (t *MyTomate) Good() {
	t.ops <- func() {
		t.embed.Good()
	}
	<-t.tick
}

// Name is channeled
func (t *MyTomate) Name(it string) string {
	var retVar0 string
	t.ops <- func() {
		retVar0 = t.embed.Name(it)
	}
	<-t.tick
	return retVar0
}
