package main

// file generated by
// github.com/mh-cbon/channeler
// do not edit

// MyTomatePointer is channeled.
type MyTomatePointer struct {
	embed *Tomate
	ops   chan func()
	stop  chan bool
	tick  chan bool
}

// NewMyTomatePointer constructs a channeled version of *Tomate
func NewMyTomatePointer(n string) *MyTomatePointer {
	ret := &MyTomatePointer{
		ops:  make(chan func()),
		tick: make(chan bool),
		stop: make(chan bool),
	}
	ret.embed = NewTomate(n)
	go ret.Start()
	return ret
}

// Start the main loop
func (t *MyTomatePointer) Start() {
	for {
		select {
		case op := <-t.ops:
			op()
			t.tick <- true
		case <-t.stop:
			return
		}
	}
}

// Stop the main loop
func (t *MyTomatePointer) Stop() {
	t.stop <- true
}

// Hello is channeled
func (t *MyTomatePointer) Hello() {
	t.ops <- func() {
		t.embed.Hello()
	}
	<-t.tick
}

// Good is channeled
func (t *MyTomatePointer) Good() {
	t.ops <- func() {
		t.embed.Good()
	}
	<-t.tick
}

// Name is channeled
func (t *MyTomatePointer) Name(it string) string {
	var retVar1 string
	t.ops <- func() {
		retVar1 = t.embed.Name(it)
	}
	<-t.tick
	return retVar1
}
